import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {makeProject,makeCommand,fullScope} from '../src/pose/state.js';
const api=await import('../src/pose/engine.js').catch(()=>({}));
const profile=JSON.parse(readFileSync(new URL('../assets/profiles/primary.json',import.meta.url)));profile.assetRef={id:profile.id,sha256:'1'.repeat(64),relativePath:'profiles/primary.json'};
const model=JSON.parse(readFileSync(new URL('../assets/model-source-a.json',import.meta.url)));
function setup(){assert.equal(typeof api.createEngine,'function');const p=makeProject(model,profile);return api.createEngine(p,profile);}
const bend={rightLowerLeg:[Math.sin(.7),0,0,Math.cos(.7)]};
for(const source of ['preset','slider','drag','mirror','clip'])test(source+' cannot reverse-bend knee',()=>{const e=setup(),p=e.read();const r=e.apply(makeCommand(p,[{kind:'patch',value:{rotations:bend}}],fullScope(p),source));assert.equal(r.status,'applied');assert.ok(Math.abs(e.read().snapshot.rotations.rightLowerLeg[0])<1e-6);assert.ok(r.issues.some(x=>x.code==='JOINT_LIMIT'));});
test('preview is isolated; restore refuses illegal knees instead of silently repairing',()=>{const e=setup(),p=e.read();e.preview(makeCommand(p,[{kind:'patch',value:{rotations:bend}}],fullScope(p)));assert.deepEqual(e.read(),p);const bad=structuredClone(p);Object.assign(bad.snapshot.rotations,bend);assert.equal(e.apply(makeCommand(p,[{kind:'restore',project:bad}],fullScope(p),'load')).status,'rejected');assert.deepEqual(e.read(),p);});
test('missing limit disables edit; manual edits are retained for automatic composition',()=>{const limited=structuredClone(profile);delete limited.limits.rightHand;assert.equal(typeof api.createEngine,'function');const p=makeProject(model,limited),e=api.createEngine(p,limited);assert.equal(e.apply(makeCommand(p,[{kind:'patch',value:{rotations:{rightHand:[0,0,.1,Math.sqrt(.99)]}}}],fullScope(p))).status,'rejected');const f=setup(),first=f.read(),q=[0,0,-.1,Math.sqrt(.99)];assert.equal(f.apply(makeCommand(first,[{kind:'patch',value:{rotations:{rightIndexProximal:q}}}],fullScope(first))).status,'applied');const before=f.read();const r=f.apply(makeCommand(before,[{kind:'patch',value:{rotations:{rightIndexProximal:[0,0,0,1]}}}],fullScope(before),'preset',[]));assert.equal(r.status,'applied');assert.deepEqual(f.read().snapshot.rotations.rightIndexProximal,before.snapshot.rotations.rightIndexProximal);});
test('required foot anchors block incompatible root movement atomically',()=>{const e=setup(),p=e.read();const locks=[{kind:'anchor',bone:'leftFoot',position:[0,0,0],rotation:[0,0,0,1]}];const r=e.apply(makeCommand(p,[{kind:'set-locks',value:locks}],fullScope(p)));assert.equal(r.status,'conflict');assert.deepEqual(e.read(),p);});
