import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
const api=await import('../src/pose/transactions.js').catch(()=>({}));
const stateApi=await import('../src/pose/state.js').catch(()=>({}));
const initial=JSON.parse(readFileSync(new URL('./fixtures/minimal-project.json',import.meta.url)));
const profile=JSON.parse(readFileSync(new URL('./fixtures/rig-profile.json',import.meta.url)));
const command=(id='one')=>({id,projectId:initial.projectId,expectedRevision:0,source:'slider',scope:{bones:['rightIndexProximal'],expressions:[],root:false,gaze:false,stage:false,camera:false,lighting:false},overwriteManual:['rightIndexProximal'],operations:[{kind:'patch',value:{rotations:{rightIndexProximal:[0,0,.1,Math.sqrt(.99)]}}}]});
function tx(){assert.equal(typeof api.createTransactions,'function');return api.createTransactions(initial);}
const change=p=>{p.snapshot.rotations.rightIndexProximal=[0,0,.1,Math.sqrt(.99)];return{project:p,issues:[]};};
test('duplicates cannot execute twice and stale commands cannot overwrite newer edits',()=>{const t=tx();const c=command();const once=t.run(c,change);assert.equal(once.status,'applied');assert.deepEqual(t.run(c,()=>{throw Error('must not execute');}),once);assert.equal(t.run(command('two'),change).status,'conflict');assert.equal(t.read().revision,1);});
test('same id with different contents is rejected',()=>{const t=tx();t.run(command(),change);const other=command();other.source='drag';assert.equal(t.run(other,change).status,'rejected');});
test('a producer cannot change the opposite hand outside its scope',()=>{const t=tx();const r=t.run(command(),p=>{p.snapshot.rotations.leftHand=[0,.1,0,Math.sqrt(.99)];return{project:p,issues:[]};});assert.equal(r.status,'rejected');assert.deepEqual(t.read(),initial);});
test('failed compound edits leave the complete previous state intact',()=>{const t=tx();const r=t.run(command(),p=>{p.snapshot.rootPosition[1]=10;throw Error('cannot reach');});assert.equal(r.status,'rejected');assert.deepEqual(t.read(),initial);});
test('undo and redo restore an operation atomically with monotonic revisions',()=>{const t=tx();t.run(command(),change);const modified=t.read().snapshot;const undo={...command('undo'),expectedRevision:1,operations:[{kind:'undo'}]};assert.equal(t.run(undo,p=>({project:p,issues:[]})).status,'applied');assert.deepEqual(t.read().snapshot,initial.snapshot);assert.equal(t.read().revision,2);assert.equal(t.run({...undo,id:'redo',expectedRevision:2,operations:[{kind:'redo'}]},p=>({project:p,issues:[]})).status,'applied');assert.deepEqual(t.read().snapshot,modified);assert.equal(t.read().revision,3);});
test('malformed numbers, zero quaternions, unknown bones and invalid weights are rejected',()=>{assert.equal(typeof stateApi.checkProject,'function');for(const mutate of[p=>p.snapshot.rootPosition[0]=NaN,p=>p.snapshot.rootPosition[2]=Infinity,p=>p.snapshot.rotations.head=[0,0,0,0],p=>p.snapshot.rotations.unknownBone=[0,0,0,1],p=>p.snapshot.expressions.happy=2,p=>p.camera.width=-1]){const p=structuredClone(initial);mutate(p);assert.ok(stateApi.checkProject(p,profile).some(i=>i.severity==='error'));}});
test('locked joint and lock list cannot be silently rewritten by a pose',()=>{assert.equal(typeof api.createTransactions,'function');const locked=structuredClone(initial);locked.snapshot.locks=[{kind:'joint',bone:'rightIndexProximal',rotation:[0,0,0,1]}];const t=api.createTransactions(locked);assert.equal(t.run(command(),change).status,'conflict');assert.equal(t.run(command('erase'),p=>{p.snapshot.locks=[];return{project:p,issues:[]};}).status,'rejected');assert.deepEqual(t.read(),locked);});
