import{poseParts,buildPoseCommand}from'../assets/pose-library.js';import{sampleAsset}from'../assets/sampling.js';import{searchAssets}from'../assets/catalog.js';import{createPosePreviewer}from'./pose-preview.js';
export function mountPoseLibrary({host,client,avatar,profile,catalog,model,run}){
 let mode='builtin',personal=[],disposed=false,previewer;
 const preview=()=>previewer||(previewer=createPosePreviewer({model,profile,catalog}));
 host.innerHTML='<div class="eyebrow">POSE LIBRARY</div><h2>姿势与收藏</h2><div class="library-tabs"><button data-library="builtin" aria-pressed="true">常用姿势</button><button data-library="mine" aria-pressed="false">我的收藏</button></div><input id="search" placeholder="查找动作或收藏名称" aria-label="查找动作"><button id="collect-pose" class="collect">＋ 收藏当前姿势</button><details class="keep-options"><summary>应用时保留哪些调整</summary><label><input type="checkbox" id="keep-hands" checked> 保留当前手型</label><label><input type="checkbox" id="keep-face" checked> 保留头颈和表情</label><label><input type="checkbox" id="keep-manual" checked> 保留手工微调</label><p class="subtle">以上选项用于全身与身体姿势。单独选择一只手、头颈或手臂会替换该部位；锁定始终生效。</p></details><div id="library-status" role="status"></div><div id="assets"></div><button id="pose-gallery">查看动作多视图</button><label class="subtle">动画取帧时间（秒）<input id="frame" type="number" value="1.5" min="0" max="20" step=".1"></label><details><summary>素材来源与适配</summary><p class="subtle">预览展示完整动作；应用时以勾选的保留项和当前锁定为准。姿势按本角色适配，未检查的条目标为候选。</p><div id="sources"></div></details><div class="note">在当前 Codex 对话里描述动作，先摆出，再拖动微调。收藏姿势供以后组合；“保存项目”保留整个现场。</div>';
 const status=host.querySelector('#library-status'),list=host.querySelector('#assets'),search=host.querySelector('#search');
 const settings=()=>({preserveHands:host.querySelector('#keep-hands').checked,preserveFace:host.querySelector('#keep-face').checked,preserveManual:host.querySelector('#keep-manual').checked});
 const setMode=value=>{mode=value;for(const b of host.querySelectorAll('[data-library]'))b.setAttribute('aria-pressed',String(b.dataset.library===mode));draw();};
 for(const b of host.querySelectorAll('[data-library]'))b.onclick=()=>setMode(b.dataset.library);
 const itemFor=(asset,value,p=client.read())=>{const {layers,...patch}=value;return{schemaVersion:1,id:asset.id,name:asset.name,part:asset.part||'body',patch,model:p.model,profile:p.profile,sources:[asset.id]};};
 function draw(){
  const all=mode==='mine'?personal:catalog,q=search.value.trim();const matches=q?searchAssets(q,{...profile.capabilities,contacts:['floor','chair']},all):all.map(a=>({assetId:a.id}));list.replaceChildren();
  if(!matches.length){const empty=document.createElement('p');empty.className='subtle';empty.textContent=mode==='mine'?'还没有收藏。摆好姿势后，点击上方“收藏当前姿势”。':'没有找到这个动作';list.append(empty);}
  for(const match of matches){const asset=all.find(a=>a.id===match.assetId),card=document.createElement('button');card.className='asset pose-card';card.setAttribute('aria-label','应用 '+asset.name);card.disabled=!!asset.unavailable||!!match.missing?.length;
   const img=document.createElement('img');img.alt=asset.name+'真实预览';img.src=mode==='mine'?'/api/pose-images/'+asset.id+'.png':asset.thumbnail;img.loading='lazy';img.onerror=()=>{img.hidden=true;};img.onload=()=>{img.hidden=false;};
   const body=document.createElement('span'),name=document.createElement('strong'),detail=document.createElement('small');name.textContent=asset.name;detail.textContent=(match.approximate?'近似候选 · ':'')+(asset.unavailable?asset.reason:mode==='mine'?poseParts[asset.part]:asset.qualification==='candidate'?'待检查 · '+asset.affectedLabel:asset.affectedLabel);body.append(name,detail);card.append(img,body);
   const isPersonal=mode==='mine';card.onclick=()=>run(async()=>{if(!client.isOwner())throw Error('当前窗口只有观察权限，请重新连接');const p=client.read(),options=settings(),frame=Number(host.querySelector('#frame').value);const item=isPersonal?await client.api('/api/poses/open',{id:asset.id}):itemFor(asset,await sampleAsset(asset,frame,avatar),p);if(disposed)return;return client.send(buildPoseCommand(p,item,profile,options));});list.append(card);
  }
 }
 async function refresh(){personal=await client.api('/api/poses');if(!disposed)draw();}
 search.oninput=draw;
 host.querySelector('#collect-pose').onclick=()=>{
  const dialog=document.createElement('dialog');dialog.className='pose-save';dialog.innerHTML='<form><h2>收藏当前姿势</h2><label>名称<input name="name" aria-label="姿势名称" maxlength="60" placeholder="例如：坐着思考、右手扶额" required></label><label>保存范围<select name="part" aria-label="收藏范围"></select></label><p class="subtle">只记录所选部位；不会收藏锁定、灯光或取景。全身和身体姿势会记录对应的椅子与地面支撑。</p><p class="save-status" role="status"></p><div class="row"><button type="button" data-cancel>取消</button><button class="primary" type="submit">保存收藏</button></div></form>';document.body.append(dialog);
  for(const[id,name]of Object.entries(poseParts)){const o=document.createElement('option');o.value=id;o.textContent=name;dialog.querySelector('select').append(o);}const currentPart=document.querySelector('#region').value;dialog.querySelector('select').value=poseParts[currentPart]?currentPart:'full';
  dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove(),{once:true});
  dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const submit=dialog.querySelector('[type=submit]'),message=dialog.querySelector('.save-status'),name=dialog.querySelector('input').value.trim(),part=dialog.querySelector('select').value;if(!name)return;
   submit.disabled=true;try{if(!client.isOwner())throw Error('请先连接可编辑窗口');const p=client.read();message.textContent='正在为这个姿势生成真实预览…';const thumbnail=await preview().capture(p,part);const saved=await client.api('/api/poses/save',{expectedRevision:p.revision,name,part,thumbnail});await refresh();search.value='';setMode('mine');status.textContent='已收藏“'+saved.name+'”';dialog.close();}catch(err){message.textContent=err.message;message.className='save-status error';}finally{submit.disabled=false;}
  };dialog.showModal();dialog.querySelector('input').focus();
 };
 for(const a of catalog){const paragraph=document.createElement('p'),link=document.createElement('a'),small=document.createElement('small');link.textContent=a.name;link.href=a.source;link.target='_blank';link.rel='noreferrer';small.textContent=a.type==='vrma'?'已有动画，按所选时刻取姿势':['look-left','head-down','hands-behind-head'].includes(a.id)?'在现有角色上制作的局部动作':'现成姿势参考，经当前角色适配';paragraph.append(link,document.createElement('br'),small);host.querySelector('#sources').append(paragraph);}
 host.querySelector('#pose-gallery').onclick=()=>run(async()=>{
  const dialog=document.createElement('dialog');dialog.className='gallery pose-gallery';dialog.innerHTML='<div class="gallery-head"><h2>动作多视图 · 真实角色</h2><button>关闭</button></div><p class="subtle">独立角色预览，不改变当前项目。每一行依次为正面、侧面、背面。</p><div class="gallery-status"></div><div class="gallery-grid"></div>';document.body.append(dialog);dialog.showModal();let stop=false;dialog.querySelector('button').onclick=()=>{stop=true;dialog.close();};dialog.addEventListener('close',()=>{stop=true;dialog.remove();},{once:true});
  for(const a of catalog.filter(x=>x.type==='pose'))for(const view of ['front','side','back']){if(stop||disposed)return;const {image}=await preview().asset(a,view);await client.api('/api/library-previews',{id:a.id,assetSha256:a.sha256,view,image});const card=document.createElement('a'),img=document.createElement('img'),text=document.createElement('span');card.href=image;card.target='_blank';img.src=image;img.alt=a.name+' '+view;text.textContent=a.name+' · '+({front:'正面',side:'侧面',back:'背面'})[view];card.append(img,text);dialog.querySelector('.gallery-grid').append(card);dialog.querySelector('.gallery-status').textContent='已生成 '+dialog.querySelectorAll('.gallery-grid a').length+' 个视图';}
 });
 draw();refresh().catch(e=>{status.textContent=e.message;});
 (async()=>{let count=0;for(const asset of catalog){if(disposed)return;try{const cached=await fetch(asset.thumbnail);if(cached.ok)continue;status.textContent='正在生成动作预览 '+(++count);const {image}=await preview().asset(asset);await client.api('/api/library-previews',{id:asset.id,assetSha256:asset.sha256,image});if(!disposed)draw();}catch(e){if(!disposed)status.textContent='预览未完成：'+e.message;return;}}if(!disposed)status.textContent='预览已就绪 · '+catalog.length+' 个动作';})();
 return{dispose(){disposed=true;previewer?.dispose();},refresh};
}
